### PR TITLE
Allows querying nested subcollection groups

### PR DESCRIPTION
**Pull request by hotchpotch**
Hi!

I want to use nested subcollection in `query()`.

```
const allPosts = group('posts', [nestedPost]) // nestedPost is NestedSubcollection
const posts = await query(allPosts, [])
```

### CODE REVIEW

**Comment by hotchpotch** [comment]
@kossnocorp How about this? 😃

**Comment by kossnocorp** [comment]
@hotchpotch so sorry about the delay, I've missed the original email notification. Will merge and ship it!

**Comment by hotchpotch** [comment]
Thank you !

**Comment by jordansilva** [comment]
Hi, I'm also trying to make groups work with NestedSubcollection. Is there any reason why this PR wasn't merged yet? Or are more changes needed to make it work?

**Comment by hotchpotch** [comment]
@kossnocorp if that’s all right with you, merge please 🙏

**Comment by kossnocorp** [comment]
@hotchpotch so sorry about that, I was away from open-source for a while.

**Comment by hotchpotch** [comment]
@kossnocorp thanks for merged this PR 😄 !

**Pull request merged**
