### PR TITLE
Export batch interface

### PR DESCRIPTION
**Pull request by kossnocorp**
See https://github.com/kossnocorp/typesaurus/issues/6#issuecomment-569524596

### CODE REVIEW

**Comment by kossnocorp** [comment]
@niklasravnsborg let's continue the discussion on [your comment](https://github.com/kossnocorp/typesaurus/issues/6#issuecomment-569524596) here.

I like the idea, and it was pretty easy to implement. I've shipped it as `4.1.0-beta`, please try and tell me if it works for you.

**Comment by kossnocorp** [comment]
I've shipped v4.1.0

**Comment by niklasravnsborg** [comment]
@kossnocorp Hey Sasha, I tried to use the type – works like a charm!

We are currently building an API product which uses Firestore on the backend completely. We had to do a somewhat big refactor because we used the wrong Firebase libraries in our Node.js backend by accident (used web js libraries). In the refactor we are also moving the entire codebase to use Typesaurus. So maybe you will see more feedback from us in the future!

Thank you and have a good week 🧑‍💻

**Comment by kossnocorp** [comment]
@niklasravnsborg amazing, I glad it worked for you!

Btw, I work on another project for Firestore — [Backup Fire](https://backupfire.dev/). It's maintained backup service for Firestore. Check it out. It might be useful for your project!

**Comment by niklasravnsborg** [comment]
@kossnocorp Awesome! I already saw it as a sponsor on the Typesaurus website. Will look into it ;)

**Comment by kossnocorp** [comment]
@niklasravnsborg thanks, yup that's me sponsoring myself, haha.

**Pull request merged**
